server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/psm
    username: postgres
    password: postgres

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate